// ============================================================
// PrismPane — Dark Mode Editor Theme Definitions
// ============================================================

import type { EditorTheme } from '../../types';

/**
 * Six carefully crafted colorful dark themes, each with distinct personality.
 * Every color is hand-picked for vibrant contrast on dark backgrounds.
 */

export const THEMES: EditorTheme[] = [
  {
    id: 'neon-nebula',
    name: 'Neon Nebula',
    editorClassName: 'theme-neon-nebula',
    baseTheme: 'custom',
    colors: {
      background: '#0d0b14',
      foreground: '#f1e6ff',
      cursor: '#ff00ff',
      selection: '#ff00ff33',
      selectionMatch: '#ff00ff40',
      selectionText: '#ff00ff',
      gutterBackground: '#08070d',
      gutterForeground: '#8a77a6',
      lineHighlight: '#1a1628',
      heading: '#ff00ff',
      heading1: '#00ffff',
      heading2: '#ff0055',
      heading3: '#ffaa00',
      bold: '#ff00aa',
      italic: '#00ffcc',
      boldItalic: '#ff00ff',
      link: '#00ffff',
      linkText: '#00ffff',
      code: '#33ff33',
      codeBackground: '#1a1628',
      blockquote: '#a89ebd',
      blockquoteBorder: '#ff00ff',
      list: '#ffaa00',
      hr: '#332a4d',
      strikethrough: '#8a77a6',
      image: '#00ffff',
      sidebarBackground: '#08070d',
      sidebarForeground: '#e0d1ff',
      toolbarBackground: '#0a0910',
      toolbarForeground: '#e0d1ff',
      activeTab: '#ff00ff',
      inactiveTab: '#8a77a6',
      tabSavedColor: '#33ff33',
      tabUnsavedColor: '#ffaa00',
      tabSavedText: '#a89ebd',
      tabUnsavedText: '#ffffff',
    },
  },
  {
    id: 'cyberpunk-glow',
    name: 'Cyberpunk Glow',
    editorClassName: 'theme-cyberpunk-glow',
    baseTheme: 'custom',
    colors: {
      background: '#050510',
      foreground: '#e5e5f0',
      cursor: '#fcee0a',
      selection: '#fcee0a33',
      selectionMatch: '#fcee0a40',
      selectionText: '#fcee0a',
      gutterBackground: '#020208',
      gutterForeground: '#5b5b7a',
      lineHighlight: '#101021',
      heading: '#fcee0a',
      heading1: '#ff003c',
      heading2: '#00f0ff',
      heading3: '#ff00ea',
      bold: '#ff003c',
      italic: '#00f0ff',
      boldItalic: '#fcee0a',
      link: '#00f0ff',
      linkText: '#00f0ff',
      code: '#00ff9d',
      codeBackground: '#101021',
      blockquote: '#7f7f99',
      blockquoteBorder: '#fcee0a',
      list: '#ff00ea',
      hr: '#1b1b36',
      strikethrough: '#5b5b7a',
      image: '#00f0ff',
      sidebarBackground: '#020208',
      sidebarForeground: '#cccccc',
      toolbarBackground: '#03030b',
      toolbarForeground: '#cccccc',
      activeTab: '#fcee0a',
      inactiveTab: '#5b5b7a',
      tabSavedColor: '#00ff9d',
      tabUnsavedColor: '#ff00ea',
      tabSavedText: '#7f7f99',
      tabUnsavedText: '#ffffff',
    },
  },
  {
    id: 'enchanted-forest',
    name: 'Enchanted Forest',
    editorClassName: 'theme-enchanted-forest',
    baseTheme: 'custom',
    colors: {
      background: '#08120b',
      foreground: '#e2f0e6',
      cursor: '#66ff00',
      selection: '#66ff0033',
      selectionMatch: '#66ff0040',
      selectionText: '#66ff00',
      gutterBackground: '#040a06',
      gutterForeground: '#608a6b',
      lineHighlight: '#0d1f13',
      heading: '#ffcc00',
      heading1: '#00ffa6',
      heading2: '#a6ff00',
      heading3: '#00e5ff',
      bold: '#ffcc00',
      italic: '#00ff99',
      boldItalic: '#a6ff00',
      link: '#00e5ff',
      linkText: '#00e5ff',
      code: '#ff9900',
      codeBackground: '#0d1f13',
      blockquote: '#82ab8f',
      blockquoteBorder: '#ffcc00',
      list: '#00e5ff',
      hr: '#163321',
      strikethrough: '#608a6b',
      image: '#a6ff00',
      sidebarBackground: '#040a06',
      sidebarForeground: '#c9decb',
      toolbarBackground: '#060e08',
      toolbarForeground: '#c9decb',
      activeTab: '#ffcc00',
      inactiveTab: '#608a6b',
      tabSavedColor: '#00ffa6',
      tabUnsavedColor: '#ff9900',
      tabSavedText: '#82ab8f',
      tabUnsavedText: '#ffffff',
    },
  },
  {
    id: 'electric-ocean',
    name: 'Electric Ocean',
    editorClassName: 'theme-electric-ocean',
    baseTheme: 'custom',
    colors: {
      background: '#020814',
      foreground: '#d9f0ff',
      cursor: '#00e5ff',
      selection: '#00e5ff33',
      selectionMatch: '#00e5ff40',
      selectionText: '#00e5ff',
      gutterBackground: '#01050d',
      gutterForeground: '#4a6e99',
      lineHighlight: '#071633',
      heading: '#00ccff',
      heading1: '#00ffcc',
      heading2: '#0088ff',
      heading3: '#ff00a0',
      bold: '#00ffcc',
      italic: '#00e5ff',
      boldItalic: '#00ccff',
      link: '#0088ff',
      linkText: '#0088ff',
      code: '#a3ff00',
      codeBackground: '#071633',
      blockquote: '#85a3cc',
      blockquoteBorder: '#00ccff',
      list: '#ff00a0',
      hr: '#0f295c',
      strikethrough: '#4a6e99',
      image: '#00ffcc',
      sidebarBackground: '#01050d',
      sidebarForeground: '#b3d9ff',
      toolbarBackground: '#010610',
      toolbarForeground: '#b3d9ff',
      activeTab: '#00e5ff',
      inactiveTab: '#4a6e99',
      tabSavedColor: '#a3ff00',
      tabUnsavedColor: '#ff00a0',
      tabSavedText: '#85a3cc',
      tabUnsavedText: '#ffffff',
    },
  },
  {
    id: 'crimson-supernova',
    name: 'Crimson Supernova',
    editorClassName: 'theme-crimson-supernova',
    baseTheme: 'custom',
    colors: {
      background: '#120204',
      foreground: '#ffe5e9',
      cursor: '#ff0000',
      selection: '#ff000033',
      selectionMatch: '#ff000040',
      selectionText: '#ff0000',
      gutterBackground: '#0a0102',
      gutterForeground: '#993344',
      lineHighlight: '#26060b',
      heading: '#ff1100',
      heading1: '#ff5500',
      heading2: '#ff0055',
      heading3: '#ffaa00',
      bold: '#ff1100',
      italic: '#ff0088',
      boldItalic: '#ff5500',
      link: '#ff0055',
      linkText: '#ff0055',
      code: '#ffff00',
      codeBackground: '#26060b',
      blockquote: '#cc7a88',
      blockquoteBorder: '#ff1100',
      list: '#ffaa00',
      hr: '#4d0c15',
      strikethrough: '#993344',
      image: '#ff5500',
      sidebarBackground: '#0a0102',
      sidebarForeground: '#ffcce0',
      toolbarBackground: '#0d0103',
      toolbarForeground: '#ffcce0',
      activeTab: '#ff1100',
      inactiveTab: '#993344',
      tabSavedColor: '#ffff00',
      tabUnsavedColor: '#ff0055',
      tabSavedText: '#cc7a88',
      tabUnsavedText: '#ffffff',
    },
  },
  {
    id: 'galactic-aurora',
    name: 'Galactic Aurora',
    editorClassName: 'theme-galactic-aurora',
    baseTheme: 'custom',
    colors: {
      background: '#090a10',
      foreground: '#e5e6ff',
      cursor: '#00ffaa',
      selection: '#00ffaa33',
      selectionMatch: '#00ffaa40',
      selectionText: '#00ffaa',
      gutterBackground: '#050508',
      gutterForeground: '#606499',
      lineHighlight: '#131526',
      heading: '#00ffaa',
      heading1: '#aa00ff',
      heading2: '#00ddff',
      heading3: '#ff00bb',
      bold: '#00ffcc',
      italic: '#bb00ff',
      boldItalic: '#00ffaa',
      link: '#00ddff',
      linkText: '#00ddff',
      code: '#ffff33',
      codeBackground: '#131526',
      blockquote: '#969acc',
      blockquoteBorder: '#00ffaa',
      list: '#ff00bb',
      hr: '#1e2240',
      strikethrough: '#606499',
      image: '#aa00ff',
      sidebarBackground: '#050508',
      sidebarForeground: '#ccceff',
      toolbarBackground: '#07080d',
      toolbarForeground: '#ccceff',
      activeTab: '#00ffaa',
      inactiveTab: '#606499',
      tabSavedColor: '#ffff33',
      tabUnsavedColor: '#ff00bb',
      tabSavedText: '#969acc',
      tabUnsavedText: '#ffffff',
    },
  },
];

/** Look up a theme by ID, falling back to the first theme. */
export function getThemeById(id: string): EditorTheme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}